spring.application.name=meeting-room-reservation
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meeting_room_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:meeting_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:meeting_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.thymeleaf.cache=false
server.port=${SERVER_PORT:8080}

app.admin.password=${APP_ADMIN_PASSWORD:admin1234}
